### PR TITLE
Remove scraping for Julia binary downloading

### PR DESCRIPTION
**Pull request by omus**
Repurposed code from the Julia Travis CI script to generate a URL rather than parse a website. Should allow us to download additional version of Julia and speed up the download process. Additionally corrects some issues with how VersionNumber was being handled.

### CODE REVIEW

**Comment by omus** [comment]
Removed an unused constant

**Comment by Rory-Finnegan** [comment]
Can you just rebase with the current dev?

**Comment by omus** [comment]
Code has been rebased to the latest dev

**Comment by Rory-Finnegan** [comment]
Thanks, looks good. Merging.

**Pull request merged**
